# Generated by Django 3.2.17 on 2023-08-04 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sitepanel.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('twitter', 'Twitter')], max_length=30)),
                ('social_id', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_username', models.CharField(max_length=255, null=True)),
                ('instagram_username', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_social', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_social',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('photo', models.ImageField(blank=True, default='user.png', null=True, upload_to='users_photo/', validators=[sitepanel.models.validate_image_extension], verbose_name='photo')),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('verified', models.BooleanField(default=0)),
                ('web_token', models.TextField(blank=True, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'User'), (4, 'seller')], default=3)),
                ('emp_code', models.CharField(max_length=15, null=True)),
                ('device_type', models.IntegerField(choices=[(1, 'Android'), (2, 'iOS'), (3, 'Web')], default=3)),
                ('otp', models.IntegerField(blank=True, default=None, null=True)),
                ('year_of_joining', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2000, message='Year of joining must be a valid year.'), django.core.validators.MaxValueValidator(2023, message='Year of joining cannot be in the future.')])),
                ('gender', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('expiry_time', models.DateTimeField()),
                ('fp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forgot_password',
            },
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('purpose', models.CharField(max_length=255)),
                ('device_type', models.IntegerField(choices=[(1, 'Android'), (2, 'iOS'), (3, 'Web')], default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
