# Generated by Django 3.2.17 on 2023-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emp_code',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
