# Generated by Django 3.2.17 on 2023-08-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
